CREATE TABLE IF NOT EXISTS dictionary_words (
                                                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                                kazakh VARCHAR(255) NOT NULL,
                                                russian VARCHAR(255) NOT NULL,
                                                english VARCHAR(255)
);

